kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: pytest-calculator
  namespace: pytest-dev
  labels:
    app: pytest-calculator
    application: pytest-calculator
spec:
  lookupPolicy:
    local: false