kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: pytest-calculator
  namespace: pytest-dev
  labels:
    app: pytest-calculator
    build: pytest-calculator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'pytest-calculator:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/python-38
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bfarr-rh/pytest-calculator.git'
      ref: master
  triggers:
    - type: ConfigChange
  runPolicy: Serial