kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:image-puller-prod-dev'
  namespace: pytest-prod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: pytest-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
