apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pytest-prod-channel
  namespace: pytest-prod
spec:
  pathname: 'https://github.com/tosin2013/pytest-calculator.git'
  type: GitHub
