apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pytest-calculator-dev-deployment-local-cluster
  namespace: pytest-prod
  labels:
    deployment: pytest-calculator-dev-deployment
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: clusters/dev/local-cluster
spec:
  channel:  pytest-prod/pytest-prod-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: local-cluster