apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pytest-calculator-dev-deployment-cluster1
  namespace: pytest-dev
  labels:
    deployment: pytest-calculator-dev-deployment
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: clusters/dev/cluster1
spec:
  channel:  pytest-dev/pytest-dev-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1